
# Site settings
title: xSong'blog
brief-intro: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://WangXianSong.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: "" 
facebook_username: "" 
github_username:  WangXianSong
email: 374155400@qq.com
weibo_username: ""
zhihu_username: ""
linkedIn_username: ""
dribbble_username: ""

description_footer: " "

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: 
disqus_shortname: xsong

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: e62093f914d33bed0e8ff16b933d1a87
#google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
